### ISSUE TITLE
Document Parcel v1.7.0 features

### ISSUE THREAD

**Issue by davidnagli** [parcel-bundler/website#132]
Parcel 1.7.0 is coming out soon, and it's gonna be a really huge update with tons of very exciting features and changes! 🚀 😃 

The only problem is... none of it is documented yet 😟 

I think we should all work together on getting the major changes documented in depth:
- [ ]  **New Resolver** (parcel-bundler/parcel#850) - Explain tilde/absolute paths, aliases, etc.
- [ ]  **Auto Install Feature**  (parcel-bundler/parcel#805) - There's not much to explain, but it's still new concept so we're gonna need to document what it and why it's useful
- [ ] **New File Naming Strategy**  (parcel-bundler/parcel#1025) - We should add something to the advanced documentation with that table that @jamiebuilds made in the PR comments

Lmk if I missed anything else that needs to be documented.

**Comment by devongovett** [comment]
* GLSL assets
* New default public url (probably change the one here to something else https://parceljs.org/production.html#set-the-public-url-to-serve-on)
* Custom SSL certificate options

**Comment by DeMoorJasper** [comment]
* Update https://parceljs.org/asset_types.html to the improved pipeline api

**Comment by item4** [comment]
I think you missed about`.vue` file support and `--log-level`

**Comment by wesleyboar** [comment]
[1.70 has been released](https://github.com/parcel-bundler/parcel/releases). I am very much looking forward to some documentation. Where should I ask for help until that documentation is available?

> I am trying to use `~/` for protject-root-relative paths—and I am failing…
> 
> ```
> /omg/absolute/path/scripts/src/site/site.js:21:28: Cannot resolve dependency '~/src/site/visual/is-logged-in.js' at '/omg/absolute/path/scripts/src/site/~/src/site/visual/is-logged-in.js'
> ```
> 
> The nearest `package.json` is at `/omg/absolute/path/scripts/package.json`.

**Comment by TimNZ** [comment]
The docs have been for 1.7.0 for around a week.

A prominent version number on the docs pages would be helpful.

Devon blogged on 1.7.0.
https://medium.com/@devongovett/parcel-v1-7-0-9aac0c505837

A **Blogs** or **Releases** link on the landing page along with current version number would be useful

**Comment by davidnagli** [comment]
@wesleyboar I think most things should be documented, but if you ever run into something you need help with you can always message us on the Parcel slack :)
